Fiz os ajustes da api para a tela de login e está funcionando
Projeto-grupo-05/projeto pull request #20
Opened 2023-04-06 15:01 UTC by sitavares

2023-04-06 15:15 UTC, emilliedev requested changes
Acredito que o botão de sair da tela interna devia limpar a session storage, mas com exceção a isso está funcionando perfeitamente!

2023-04-06 15:16 UTC, emilliedev approved these changes
Tudo funcionando perfeitamente

2023-04-11 13:52 UTC, NatanFigueira approved these changes
Temos que lembrar de tirar o id do usuario e da empresa quando o usuario dá logout. Sei que não é dessa tela, mas é bom lembrar. Login fico legal

2023-04-15 01:52 UTC, JoaoLimaHeyla approved these changes
muy bom

2023-04-15 01:57 UTC, NatanFigueira approved these changes

2023-04-15 01:58 UTC, merged